### ISSUE TITLE
Lastest TypeScript Version Supporting Noir ^0.4.0?

### ISSUE THREAD

**Issue by glthr** [noir-lang/noir#1255]
### Problem

In a context of a JavaScript project, I would like to be able to compile circuits written for Noir v0.4.0 and above.

I am using the following libraries:

- `@aztec/barretenberg 2.1.95`
- `@noir-lang/barretenberg 2.19.0`
- `@noir-lang/noir_wasm 0.3.2-fa0e9cff`

This combination seems to be incorrect:

```
panicked at 'Could not deserialize compile arguments', crates/wasm/src/lib.rs:99:33

Stack:

Error:
    at module.exports.__wbg_new_abda76e883ba8a5f (.../node_modules/.pnpm/@noir-lang+noir_wasm@0.3.2-fa0e9cff_@noir-lang+noir-source-resolver@1.1.1/node_modules/@noir-lang/noir_wasm/nodejs/noir_wasm.js:236:17)
    at null.<anonymous> (wasm://wasm/00ca78e2:1:3100381)
    at null.<anonymous> (wasm://wasm/00ca78e2:1:2844249)
    at null.<anonymous> (wasm://wasm/00ca78e2:1:3064319)
    at null.<anonymous> (wasm://wasm/00ca78e2:1:552352)
    at module.exports.compile (.../node_modules/.pnpm/@noir-lang+noir_wasm@0.3.2-fa0e9cff_@noir-lang+noir-source-resolver@1.1.1/node_modules/@noir-lang/noir_wasm/nodejs/noir_wasm.js:134:22)
    at Context.<anonymous> (.../test/factFortress.js:89:31)
    at callFn (.../node_modules/.pnpm/mocha@10.1.0/node_modules/mocha/lib/runnable.js:366:21)
    at Hook.Runnable.run (.../node_modules/.pnpm/mocha@10.1.0/node_modules/mocha/lib/runnable.js:354:5)
    at next (.../node_modules/.pnpm/mocha@10.1.0/node_modules/mocha/lib/runner.js:498:10)
    at cbHookRun (.../node_modules/.pnpm/mocha@10.1.0/node_modules/mocha/lib/runner.js:539:7)
    at done (.../node_modules/.pnpm/mocha@10.1.0/node_modules/mocha/lib/runnable.js:310:5)
    at .../node_modules/.pnpm/mocha@10.1.0/node_modules/mocha/lib/runnable.js:371:11
```

Note that a circuit < v0.4.0 compiles fine with `@noir-lang/noir_wasm 0.10.0` (but this version does not compile circuits ≥ 0.4.0).

**Do you know which combination of versions should be used?**

### Proposed solution

N/A

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Closing as this issue has become stale. Please re-open if this persists!
