### ISSUE TITLE
Recursive verification works for local verifier but not for remote

### ISSUE THREAD

**Issue by jordan-public** [noir-lang/noir#3229]
### Aim

I tried to create a proof, MARSHALL IT TO ANOTHER PROCESS and then verify it recursively in another proof. 

### Expected Behavior

The proof is generated and using verifyIntermediateProof successfully verified locally.

Then the proof is sent to another process, where the noir_js and the Barrettenberg backend is initialized the same way as in the above process. Calling verifyIntermediateProof SHOULD SUCCEED.

### Bug

Even though the proof verified with verifyIntermediateProof locally, in the other process it crashes with:

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [RuntimeError]: null function or function signature mismatch
    at wasm://wasm/01139722:wasm-function[4703]:0x18f2f1
    at wasm://wasm/01139722:wasm-function[4689]:0x18e70a
    at wasm://wasm/01139722:wasm-function[4731]:0x1908d1
    at wasm://wasm/01139722:wasm-function[1941]:0x11d1ec
    at wasm://wasm/01139722:wasm-function[2152]:0x123963
    at BarretenbergWasmMain.call (file:///Users/jordan/billion-zk-voters/count/countservice/node_modules/.pnpm/@aztec+bb.js@0.7.10/node_modules/@aztec/bb.js/dest/node/barretenberg_wasm/barretenberg_wasm_base/index.js:87:40)
    at callback (/Users/jordan/billion-zk-voters/count/countservice/node_modules/.pnpm/comlink@4.4.1/node_modules/comlink/dist/umd/comlink.js:109:52)
    at MessagePort.l (file:///Users/jordan/billion-zk-voters/count/countservice/node_modules/.pnpm/@aztec+bb.js@0.7.10/node_modules/@aztec/bb.js/dest/node/barretenberg_wasm..

### To Reproduce

I am generating an intermediate proof (which verifies OK) in the first program here: https://github.com/jordan-public/billion-zk-voters/blob/3f37b3174702bf841d2fe8c014d0fa6fc88b0fc3/vote/voteui/src/components/Body.tsx#L127

In the second program, I try to verify it using the same calls as in the first program, and it fails here: https://github.com/jordan-public/billion-zk-voters/blob/3f37b3174702bf841d2fe8c014d0fa6fc88b0fc3/count/countservice/count.js#L68 with:
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [RuntimeError]: null function or function signature mismatch
    at wasm://wasm/01139722:wasm-function[4703]:0x18f2f1
    at wasm://wasm/01139722:wasm-function[4689]:0x18e70a
    at wasm://wasm/01139722:wasm-function[4731]:0x1908d1
    at wasm://wasm/01139722:wasm-function[1941]:0x11d1ec
    at wasm://wasm/01139722:wasm-function[2152]:0x123963
    at BarretenbergWasmMain.call (file:///Users/jordan/billion-zk-voters/count/countservice/node_modules/.pnpm/@aztec+bb.js@0.7.10/node_modules/@aztec/bb.js/dest/node/barretenberg_wasm/barretenberg_wasm_base/index.js:87:40)
    at callback (/Users/jordan/billion-zk-voters/count/countservice/node_modules/.pnpm/comlink@4.4.1/node_modules/comlink/dist/umd/comlink.js:109:52)
    at MessagePort.l (file:///Users/jordan/billion-zk-voters/count/countservice/node_modules/.pnpm/@aztec+bb.js@0.7.10/node_modules/@aztec/bb.js/dest/node/barretenberg_wasm...

I am printing the proof and circuit hashes to make sure there is no error in the transfer, and they match. I am initializing the Noir and the barretenberg backend the same way. Yet, one succeeds, and the other fails as above. 

### Environment

% node --version
v18.18.0

@noir-lang/backend_barretenberg 0.7.10
@noir-lang/noir_js 0.16.0

Compiled with Noir/nargo v0.11.0 and v0.16.0. Other versions not extensively tried.

% uname -a
Darwin p21.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

### Additional Context

I also believe there are 2 other related issues:
1. Recursive proof does not verify in the generated Solidity verifier. 
2. Running the proof and verification in the same process succeeds the first time, but fails the second time (proof + verify fails; multiple verifications after the first proof work fine). 

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Closing as this no longer happens as of 0.23.0
