### ISSUE TITLE
backend_barretenberg generateProof throwing unreachable on recursive proof

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#4618]
### Aim

I want to create a proof that verifies another proof by generating the witness of the recursive inputs and feeding them to `backend_barretenberg`. Example:

```js
	const { proof, publicInputs } = await noirMain.generateProof(inputs);
	const { proofAsFields, vkAsFields, vkHash } =
		await mainBackend.generateRecursiveProofArtifacts(
			{ publicInputs, proof },
			1
		);
	const recursiveInputs = {
		verification_key: vkAsFields.map((e) => e.toString()),
		proof: proofAsFields,
		public_inputs: publicInputs,
		key_hash: vkHash,
	};

	// doesn't work
	const { recursiveWitness } = await noirRecursive.execute(recursiveInputs);
	const finalProofData = await recursionBackend.generateProof(
		recursiveWitness
	);
```

### Expected Behavior

I expect it to produce a valid proof

### Bug

Instead, it throws an unreachable error:

```
Error [RuntimeError]: unreachable
    at wasm://wasm/01fd9442:wasm-function[17622]:0x78a386
    at wasm://wasm/01fd9442:wasm-function[41]:0x2432b
    at wasm://wasm/01fd9442:wasm-function[4475]:0x1ec954
    at wasm://wasm/01fd9442:wasm-function[4477]:0x1ec9b0
    at wasm://wasm/01fd9442:wasm-function[4464]:0x1ec563
    at wasm://wasm/01fd9442:wasm-function[5751]:0x1fbbc4
    at wasm://wasm/01fd9442:wasm-function[4069]:0x1e5360
    at wasm://wasm/01fd9442:wasm-function[4066]:0x1e5269
    at wasm://wasm/01fd9442:wasm-function[4065]:0x1e5157
    at wasm://wasm/01fd9442:wasm-function[4083]:0x1e588b
```

### To Reproduce

1. [Clone this repository](https://github.com/signorecello/noir-bug-in-recursive-proofs)
2. Follow the instructions in the readme

### Project Impact

None

### Workaround

None

### Workaround Description

The workaround is to use noir generateProof directly:

```js

	// doesn't work
	const { recursiveWitness } = await noirRecursive.execute(recursiveInputs);
	const finalProofData = await recursionBackend.generateProof(
		recursiveWitness
	);

	// // works
	// const finalProofData = await noirRecursive.generateProof(recursiveInputs);

```

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment]
What are `noirRecursive` and `recursionBackend`?

**Comment by jzaki** [comment]
@Savio-Sou Reproduced in similar code on [this line](https://github.com/AztecProtocol/dev-rel/blob/jz/recursive-proofs-how-to/how-to/recursive-proofs/main.ts#L67). The first line is the console log
```
...
Generating outer proof...
Error [RuntimeError]: unreachable
    at wasm://wasm/01fea53a:wasm-function[17700]:0x78e7f4
    at wasm://wasm/01fea53a:wasm-function[223]:0x31fe6
    at wasm://wasm/01fea53a:wasm-function[226]:0x321ae
    at wasm://wasm/01fea53a:wasm-function[8451]:0x34a196
    at wasm://wasm/01fea53a:wasm-function[8450]:0x34a141
    at wasm://wasm/01fea53a:wasm-function[8449]:0x34a0fd
    at wasm://wasm/01fea53a:wasm-function[9188]:0x3d078c
    at wasm://wasm/01fea53a:wasm-function[9184]:0x3d0489
    at wasm://wasm/01fea53a:wasm-function[9180]:0x3cfd7c
    at wasm://wasm/01fea53a:wasm-function[7847]:0x2999f6
Done in 55.02s.
```

**Comment by signorecello** [comment]
> What are `noirRecursive` and `recursionBackend`?

Hey sorry indeed the example didn't instantiate them. In this example `noirRecursive` is an instance of the Noir class and `recursionBackend` is an instance of the BackendBarretenberg class

**Comment by TomAFrench** [comment]
example repository isn't debuggable.

**Comment by Savio-Sou** [comment]
Not sure if this was what @TomAFrench referred to, but this is what I get running `node main.js` on the repo:

```
% node main.js
(node:19357) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError: Cannot read properties of undefined (reading '0')
    at decompressSync (file:///.../noir-bug-in-recursive-proofs/node_modules/fflate/esm/index.mjs:1641:17)
    at BarretenbergBackend.generateProof (file:///.../noir-bug-in-recursive-proofs/node_modules/@noir-lang/backend_barretenberg/lib/esm/index.js:53:120)
    at async main (file:///.../noir-bug-in-recursive-proofs/main.js:35:25)
```
