### ISSUE TITLE
Nargo WASM compilation failure --- macOS 12.6 Monterey

### ISSUE THREAD

**Issue by michaelneuder** [noir-lang/noir#518]
# Description

Following instructions on https://noir-lang.github.io/book/getting_started/nargo/installation.html with [Option 1: WASM Executable Backend](https://noir-lang.github.io/book/getting_started/nargo/installation.html#option-1-wasm-executable-backend).

## Aim

Install Nargo.

## Expected behavior

Compile to succeed.

## Bug

For option 1: I set 

```
aztec_backend = { optional = true, git = "https://github.com/noir-lang/aztec_backend", features = ["wasm-base"] , default-features = false }
```

as described in the documentation.

Running 

```
cargo install --locked --path=.

error[E0599]: no method named `uint8view` found for reference `&wasmer::Memory` in the current scope
  --> /Users/michaelneuder/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/8dc5b28/src/barretenberg_wasm/mod.rs:51:43
   |
51 |             for (byte_id, cell) in memory.uint8view()[offset..(offset + arr.len())]
   |                                           ^^^^^^^^^ method not found in `&wasmer::Memory`

error[E0061]: this function takes 1 argument but 0 arguments were supplied
  --> /Users/michaelneuder/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/8dc5b28/src/barretenberg_wasm/mod.rs:66:23
   |
66 |         return memory.view()[start as usize..end]
   |                       ^^^^-- an argument of type `&_` is missing
   |
note: associated function defined here
  --> /Users/michaelneuder/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.0.0/src/sys/externals/memory.rs:88:12
   |
.
.
.
   --> /Users/michaelneuder/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.0.0/src/sys/instance.rs:113:12
    |
113 |     pub fn new(
    |            ^^^
help: provide the argument
    |
217 |     (Instance::new(/* value */, &module, &res_import).unwrap(), memory)
    |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Some errors have detailed explanations: E0061, E0308, E0599, E0608.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `aztec_backend` due to 20 previous errors
```

# To reproduce

(Describe the steps to reproduce the behavior.)

1. `git clone git@github.com:noir-lang/noir.git`
2. `cd noir/crates/nargo`
3. `$ cargo install --locked --path=.`

# Environment

- OS: macOS 12.6

Versions:

```
rustc --version
rustc 1.64.0 (a55dd71d5 2022-09-19)

cmake --version
cmake version 3.25.0

clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
```

For `nargo` users

- _noir-lang/noir_ commit cloned:
- Proving backend
  - [ ] default
    - Clang: (run `clang --version`)
  - [x] wasm-base

**Comment by michaelneuder** [comment]
Note that I also tried https://noir-lang.github.io/book/getting_started/nargo/installation.html#option-2-compile-backend-from-source and changed 

```
aztec_backend = { optional = true, git = "https://github.com/noir-lang/aztec_backend", rev = "01b922adcb5a9d70b2d12304e1cb7487d9f28188" }
```

Running 
```
bash -c "RUST_BACKTRACE=FULL cargo install --locked --path=."

  2 errors generated.
  make[2]: *** [src/aztec/rollup/proofs/CMakeFiles/rollup_proofs_objects.dir/account/c_bind.cpp.o] Error 1
  make[1]: *** [src/aztec/rollup/proofs/CMakeFiles/rollup_proofs_objects.dir/all] Error 2
  2 errors generated.
  make[2]: *** [src/aztec/rollup/proofs/CMakeFiles/rollup_proofs_test_objects.dir/account/account_tx.test.cpp.o] Error 1
  2 errors generated.
  make[2]: *** [src/aztec/stdlib/merkle_tree/CMakeFiles/stdlib_merkle_tree_test_objects.dir/memory_tree.test.cpp.o] Error 1
  make[1]: *** [src/aztec/stdlib/merkle_tree/CMakeFiles/stdlib_merkle_tree_test_objects.dir/all] Error 2
  2 errors generated.
  2 errors generated.
  make[2]: *** [src/aztec/rollup/proofs/CMakeFiles/rollup_proofs_test_objects.dir/escape_hatch/escape_hatch_tx.test.cpp.o] Error 1
  make[2]: *** [src/aztec/rollup/proofs/CMakeFiles/rollup_proofs_test_objects.dir/escape_hatch/escape_hatch.test.cpp.o] Error 1
  make[1]: *** [src/aztec/rollup/proofs/CMakeFiles/rollup_proofs_test_objects.dir/all] Error 2
  make: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2

  build script failed, must exit now', /Users/michaelneuder/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1104:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
     2: cmake::fail
     3: cmake::run
     4: cmake::Config::build
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to compile `nargo v0.1.0 (/Users/michaelneuder/github/noir/crates/nargo)`, intermediate artifacts can be found at `/Users/michaelneuder/github/noir/target
```

So it seems like neither installation method is working for my machine

**Comment by kobyhallx** [comment]
@michaelneuder Thanks for the report, build is currently broken

See this pre-built binary [nargo-x86_64-apple-darwin](https://github.com/kobyhallx/build-noir/suites/9452864203/artifacts/447305768).

**Comment by michaelneuder** [comment]
thanks, this is working!
