### ISSUE TITLE
ACVM `XOR` associativity test failing

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5638]
### Aim

Attempted to [test associativity of `XOR` blackbox function with `proptest`](https://github.com/noir-lang/noir/pull/5484/files#diff-6c685a553939db8389f16b6cf06d7d4caae94f46d64e327233fe02c7b4f8dbafR869):

```rust
fn prop_assert_associative(
    op: impl Fn(Option<FieldElement>, Option<FieldElement>) -> BlackBoxFuncCall<FieldElement>,
    x: (FieldElement, bool),
    y: (FieldElement, bool),
    z: (FieldElement, bool),
    use_constant_xy: bool,
    use_constant_yz: bool,
) -> (FieldElement, FieldElement) {
    let f_xy = (solve_blackbox_func_call(&op, x, y), use_constant_xy);
    let f_f_xy_z = solve_blackbox_func_call(&op, f_xy, z);

    let f_yz = (solve_blackbox_func_call(&op, y, z), use_constant_yz);
    let f_x_f_yz = solve_blackbox_func_call(&op, x, f_yz);

    (f_f_xy_z, f_x_f_yz)
}

proptest! {
    #[test]
    fn xor_associative(x in field_element(), y in field_element(), z in field_element(), use_constant_xy: bool, use_constant_yz: bool) {
        let (lhs, rhs) = prop_assert_associative(xor_op, x, y, z, use_constant_xy, use_constant_yz);
        prop_assert_eq!(lhs, rhs);
    }
}
```

### Expected Behavior

Expect the test to pass

### Bug

```bash
---- xor_associative stdout ----
thread 'xor_associative' panicked at acvm-repo/acvm/tests/solver.rs:848:1:
Test failed: assertion failed: `(left == right)` 
  left: `1283670960019916003771447463403780437091510857904449510892463880104724571074`,
 right: `944443117489026359168770680972523757203580128233348138908887269072586843074` at acvm-repo/acvm/tests/solver.rs:872.
minimal failing input: x = (
    7250061818685696343216493786193839024302863820576605192710784820741603895966,
    false,
), y = (
    -3405112893702401459380202402317574365406674719909456358229164704216370206212,
    false,
), z = (
    2⁴×300433304925226584082054090820988662109061133690344416189530074644868631050,
    false,
), use_constant_xy = false, use_constant_yz = false
	successes: 0
	local rejects: 0
	global rejects: 0

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Note that the `-` in `y = (-3405..)` is display-only: `FieldElements` wrap to non-negative values.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This is likely due to the test using differing bitsizes for the two operations which causes truncations which breaks associativity.
