### ISSUE TITLE
SyntaxError: Unexpected token 'export' when using the typescript SDK

### ISSUE THREAD

**Issue by tomoima525** [noir-lang/noir#586]
# Description

## Bug

- Can not execute typescript functions when you set `^2.19.0` (which installs 2.22.0) of `@noir-lang/barretenberg`
- This will not occur when you explicitly set `2.19.0` for `@noir-lang/barretenberg` 

```
yarn ts-node scripts/1_mul.ts
/Users/tomoima525/workspace/zkp/nargo/hello_world/.yarn/cache/@noir-lang-aztec_backend-npm-0.12.0-80b603d50b-3e41752b8a.zip/node_modules/@noir-lang/aztec_backend/aztec_backend.js:283
export function compute_witnesses(circuit, initial_js_witness) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at require$$0.Module._extensions..js (/Users/tomoima525/workspace/zkp/nargo/hello_world/.pnp.cjs:10792:33)
    at Object.require.extensions.<computed> [as .js] (/Users/tomoima525/workspace/zkp/nargo/hello_world/.yarn/__virtual__/ts-node-virtual-712c3da50c/0/cache/ts-node-npm-10.9.1-6c268be7f4-090adff130.zip/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (/Users/tomoima525/workspace/zkp/nargo/hello_world/.pnp.cjs:10629:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

# To reproduce

This is the reproducible repo https://github.com/tomoima525/noir-playground/tree/bug/noir-version
You need to setup yarn2

1. `yarn install`
2. `nargo build`
3. `yarn ts-node scripts/1_mul.ts`

# Environment

(Specify your setup and versions of dependencies.)

- OS:
For TypeScript users

- Node.js: (run `node --version`) v16.14.2
- @noir-lang/noir_wasm: (from `yarn.lock`) 0.10.0
- @noir-lang/barretenberg: (from `yarn.lock`) 2.22.0
- @noir-lang/aztec_backend: (from `yarn.lock`) 0.10.0

# Additional context

Again, this would not happen if you set 2.19.0(which supposed to be the latest) explicitly but it would cause an issue when you release 2.22.0 in the future

**Comment by kevaundray** [comment]
the typescript packages have changed a lot since this issue, so closing it for now.

If this issue persists, feel free to re-open!
